Added haptic feedback and handling for local server links for android…
DIT112-V21/group-01 pull request #42
Opened 2021-04-30 11:32 UTC by a-brannen

May need review on less updated (API 16 and below) Android devices;
Unable to see haptic feedback through emulated device in Android studio 
Closes #29

2021-05-01 15:30 UTC, dekmm requested changes

2021-05-01 15:30 UTC, dekmm commented on arduino/smartcar/secrets-default.hpp
> +
Remove file and merge with master to get the correct version of `secrets-default.hpp`

2021-05-01 15:30 UTC, dekmm commented on arduino/smartcar/smartcar.ino
Rollback changes made to the smartcar.ino file to avoid overriding the new refactor

2021-05-01 15:30 UTC, dekmm commented on client/app/src/main/java/group01/smartcar/client/CarControl.java
> +            //System.out.println("Published...");
Either uncomment or remove the comment completely

2021-05-01 15:30 UTC, dekmm commented on client/app/src/main/java/group01/smartcar/client/MainActivity.java
> +    Resources res;
Can be made private

2021-05-03 16:01 UTC, gsastraw approved these changes
good work!! just remember to take into account the merge conflicts :)

2021-05-03 23:47 UTC, dekmm approved these changes

2021-05-04 00:11 UTC, merged